version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "$MONGO_PORT:27017"
    volumes:
      - ./data/db:/data/db
      - ./mongo/init/:/var/init
      - ./mongo/mongod.conf/:/etc/mongod.conf
      - ./keys/:/var/keys
      - ./scripts/:/scripts
    links:
      - mongodb_1
      - mongodb_2
      - mongodb_arbiter
    entrypoint:
      - "./scripts/start.sh"
    command: "$MONGO_INIT_SH"
    restart: always

  mongodb_1:
    image: mongo:latest
    container_name: mongodb_1
    ports:
      - "$MONGO_PORT1:27017"
    volumes:
      - ./data/db1:/data/db
      - ./mongo/mongod.conf/:/etc/mongod.conf
      - ./keys/:/var/keys
      - ./scripts/:/scripts
    entrypoint:
      - "./scripts/start.sh"
    command: 02-secondary.sh
    restart: always

  mongodb_2:
    image: mongo:latest
    container_name: mongodb_2
    ports:
      - "$MONGO_PORT2:27017"
    volumes:
      - ./data/db2:/data/db
      - ./mongo/mongod.conf/:/etc/mongod.conf
      - ./keys/:/var/keys
      - ./scripts/:/scripts
    entrypoint:
      - "./scripts/start.sh"
    command: 02-secondary.sh
    restart: always

  mongodb_arbiter:
    image: mongo:latest
    container_name: mongodb_arbiter
    ports:
      - "$MONGO_PORT0:27017"
    volumes:
      - ./mongo/mongod.conf/:/etc/mongod.conf
      - ./keys/:/var/keys
      - ./scripts/:/scripts
    entrypoint:
      - "./scripts/start.sh"
    command: 02-secondary.sh
    restart: always
